# Generated by Django 4.2 on 2023-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0003_alter_servicio_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=250),
        ),
    ]
